runtime: java17
env: standard
instance_class: F2
handlers:
  - url: /.*
    secure: always
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: my-study-notes-389223@appspot.gserviceaccount.com